// src/components/CurrentWeather/CurrentWeather.tsx
import { FunctionComponent } from "react";
import styles from "./CurrentWeather.module.css";
import { CurrentIntro } from "./CurrentIntro";
import { CurrentItem } from "./CurrentItem";
import { TitleWithLine } from "./TitleWithLine";
import { CurrentWeatherData } from "../../domain/current-weather-entity";

export const CurrentWeather: FunctionComponent<{
  weatherData: CurrentWeatherData | null;
}> = ({ weatherData }) => {
  if (!weatherData) return <div style={{ color: "#000" }}>loading...</div>;

  return (
    <section className={styles.current}>
      <CurrentIntro
        location={weatherData.city}
        time={new Date()}
        details={{
          temperature: weatherData.temperature,
          temperatureFealing: weatherData.temperatureFealing,
          conditions: weatherData.stateDescription,
          icon: weatherData.stateIcon
        }}
      />
      <div className={styles.detail}>
        <div className={styles.detailsTitle}>
          <TitleWithLine>Detalles</TitleWithLine>
        </div>
        <CurrentItem
          value="Viento"
          content={weatherData.windSpeed.toString()}
          sub={weatherData.windAngle}
          units="km/h"
          icon="wind"
        />
        <CurrentItem
          value="Nubosidad"
          content={weatherData.clouds.toString()}
          units="%"
          icon="cloud"
        />
        <CurrentItem
          value="Humedad"
          content={weatherData.humidity.toString()}
          units="%"
          icon="raindrop"
        />
        <CurrentItem
          value="Presión"
          content={weatherData.pressure.toString()}
          units="mBar"
          icon="pressure"
        />
      </div>
      <div className={styles.detail}>
        <div className={styles.detailsTitle}>
          <TitleWithLine>Salida/Puesta de sol</TitleWithLine>
        </div>
        <CurrentItem
          value="Salida sol"
          content={weatherData.sunrise.toString()}
          icon="sunrise"
        />
        <CurrentItem
          value="Puesta sol"
          content={weatherData.sunset.toString()}
          icon="sunset"
        />
      </div>
    </section>
  );
};

// src/components/CurrentWeather/CurrentWeather.vue
<template>
  <section
    v-if="weatherData"
    class="current"
  >
    <div class="container">
      <h1 class="current--title">
        Tiempo hoy
      </h1>
      <div class="intro">
        <div class="location">
          {{ weatherData.city }}
        </div>
        <div class="time">
          {{ weatherData.hour }} — {{ weatherData.date }}
        </div>

        <div class="temp">
          <span>{{ Math.round(weatherData.temperature) }}</span>
          <span class="temp-symbol">º</span>
        </div>

        <div class="conditions">
          <component
            :is="weatherData.stateIcon"
            class="conditions-icon"
          />
          <span>{{ weatherData.stateDescription }}</span>
        </div>
      </div>
      <div class="details">
        <TitleWithLine
          content="Detalles"
          class="details--title"
        />
        <CurrentItem
          title="Viento"
          :content="weatherData.windSpeed.toString()"
          :sub="weatherData.windAngle"
          units="km/h"
          icon="icon-wind"
        />
        <CurrentItem
          title="Nubosidad"
          :content="weatherData.clouds.toString()"
          units="%"
          icon="icon-cloud"
        />
        <CurrentItem
          title="Humedad"
          :content="weatherData.humidity.toString()"
          units="%"
          icon="icon-raindrop"
        />
        <CurrentItem
          title="Presión"
          :content="weatherData.pressure.toString()"
          units="mBar"
          icon="icon-pressure"
        />
      </div>
      <div class="details">
        <TitleWithLine
          content="Salida/Puesta de sol"
          class="details--title"
        />
        <CurrentItem
          title="Salida sol"
          :content="weatherData.sunrise.toString()"
          icon="icon-sunrise"
        />
        <CurrentItem
          title="Puesta sol"
          :content="weatherData.sunset.toString()"
          icon="icon-sunset"
        />
      </div>
      <div class="log">
        {{ weatherData }}
      </div>
    </div>
  </section>
</template>

<script>
import CurrentItem from "@/components/CurrentItem";
import TitleWithLine from "@/components/TitleWithLine";

export default {
  name: "CurrentWeather",
  components: { CurrentItem, TitleWithLine },
  props: {
    weatherData: {
      type: Object,
      default: () => {}
    },
  },
};
</script>

<style lang="postcss" scoped>
@import "../../assets/styles/helpers/variables";
@import "./CurrentWeather";
</style>
