// src/App/Current/CurrentItem.tsx
import React, { CSSProperties, FunctionComponent } from "react";
import { getDirection } from "../../utils";

export type CurrentItemType = {
  value: string;
  sub?: number;
  content: string;
  units?: string;
  icon: string;
};

const CurrentItem: FunctionComponent<CurrentItemType> = ({
  value,
  sub,
  content,
  units,
  icon
}) => {
  return (
    <div style={itemStyles}>
      <div style={contentStyles}>
        <div style={titleStyles}>{value}</div>
        {!!sub && (
          <span style={subStyles} data-testid="direction">
            {getDirection(sub)}
          </span>
        )}
        {content}
        {units && <span style={unitsStyles}> {units}</span>}
      </div>
      <div style={iconStyles}>{icon}</div>
    </div>
  );
};

const itemStyles: CSSProperties = {
  display: "grid",
  gridTemplateColumns: "1fr auto",
  alignItems: "center",
  padding: "20px 10px 5px",
  background: "hsl(0deg 0% 100% / 5%)",
  borderRadius: 3
};
const contentStyles: CSSProperties = {
  position: "relative",
  fontSize: 18,
  fontWeight: 800
};
const titleStyles: CSSProperties = {
  position: "absolute",
  bottom: "100%",
  left: "0",
  fontSize: 12,
  fontWeight: 300
};
const unitsStyles: CSSProperties = { fontSize: 12 };
const subStyles: CSSProperties = { fontSize: 13, marginRight: 5 };
const iconStyles: CSSProperties = { fontSize: 40 };

export { CurrentItem };

// src/components/Current/CurrentItem.vue
<template>
  <div class="item">
    <div class="content">
      <div class="title">
        {{ title }}
      </div>
      <span
        v-if="sub"
        class="sub"
      >{{ sub }}</span>
      {{ content }}
      <span
        v-if="units"
        class="units"
      >{{ units }}</span>
    </div>
    <div class="icon">
      <component :is="icon" />
    </div>
  </div>
</template>

<script>
export default {
  name: "CurrentItem",
  props: {
    title: {
      type: String,
      default: ""
    },
    sub: {
      type: String,
      default: ""
    },
    content: {
      type: String,
      default: ""
    },
    units: {
      type: String,
      default: ""
    },
    icon: {
      type: String,
      default: ""
    },
  },
};
</script>

<style lang="postcss" scoped>
@import "../../assets/styles/helpers/variables";

.item {
  display: grid;
  grid-template-columns: 1fr auto;
  align-items: center;
  padding: 20px 10px 5px;
  background: color-mod(var(--light-color) a(5%));
  border-radius: 3px;
}

.content {
  position: relative;
  font-size: 18px;
  font-weight: 800;
}

.title {
  position: absolute;
  bottom: 100%;
  left: 0;
  font-size: 12px;
  font-weight: 300;
}

.units {
  font-size: 12px;
}

.sub {
  font-size: 13px;
}

.icon {
  font-size: 40px;
}
</style>
